### ISSUE TITLE
Remove the horizontal lines from the navbar when the sidebar is hidden

### ISSUE THREAD

**Issue by jrgns** [EagerELK/ditty#3]
In a small enough browser window the sidebar will be hidden, but for some reason there's two extra horizontal lines in the navbar:

![image](https://user-images.githubusercontent.com/170848/31057664-edd8f9fa-a6e6-11e7-880d-aa9c46d559de.png)

Make them disappear.

**Comment by jamesday7** [comment]
I've got a fix for this I'll create a PR when I wake up and have had coffee.

**Comment by jrgns** [comment]
@jamesday7 Still interested in doing this?
