### ISSUE TITLE
Add rubocop to the Travis build and resolve all W errors and higher 

### ISSUE THREAD

**Issue by jrgns** [EagerELK/ditty#5]
Add the following command to the travis build, before the specs run:

```
bundle exec rubocop --fail-level W lib views
```

Ensure that the build passes by fixing all `W` and higher errors.

**Comment by Atul9** [comment]
I would like to take this up.

**Comment by Atul9** [comment]
I tried to fix few of the warning from rubocop. - https://travis-ci.org/Atul9/ditty/jobs/287892912

**Comment by jrgns** [comment]
Fixed in PR #6
